// Code generated by "stringer -type ErrorType -output ./stringer_errortype.go"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUndefined-0]
	_ = x[ErrEmptyString-1]
	_ = x[ErrEmptyArray-2]
	_ = x[ErrWebUnknownMethod-3]
	_ = x[ErrWebApiNotInit-4]
	_ = x[ErrWebGroupExists-5]
	_ = x[ErrWebGroupNotExists-6]
}

const _ErrorType_name = "ErrUndefinedErrEmptyStringErrEmptyArrayErrWebUnknownMethodErrWebApiNotInitErrWebGroupExistsErrWebGroupNotExists"

var _ErrorType_index = [...]uint8{0, 12, 26, 39, 58, 74, 91, 111}

func (i ErrorType) String() string {
	if i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
