// Code generated by "stringer -type ResponseErrorId -output ./stringer_ResponseErrorId.go"; DO NOT EDIT.

package web_response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RespErrNone-0]
	_ = x[RespErrUndefined-1]
}

const _ResponseErrorId_name = "RespErrNoneRespErrUndefined"

var _ResponseErrorId_index = [...]uint8{0, 11, 27}

func (i ResponseErrorId) String() string {
	if i >= ResponseErrorId(len(_ResponseErrorId_index)-1) {
		return "ResponseErrorId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseErrorId_name[_ResponseErrorId_index[i]:_ResponseErrorId_index[i+1]]
}
