// Code generated by "stringer -type ResponseId -output ./stringer_ResponseId.go"; DO NOT EDIT.

package web_response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RespSccsGeneric-0]
	_ = x[RespSccsLogin-1]
	_ = x[RespSccsLogout-2]
	_ = x[RespSccsSignup-3]
	_ = x[RespScssSignupEmailConfirm-4]
	_ = x[RespSccsAlreadyLoggedIn-5]
	_ = x[RespErrUndefined-6]
	_ = x[RespErrUnknownInternal-7]
	_ = x[RespErrCsrfInvalid-8]
	_ = x[RespErrUserDoesNotExist-9]
	_ = x[RespErrUserNoRoles-10]
	_ = x[RespErrMissingInput-11]
	_ = x[RespErrJwtAccessTokenSigning-12]
	_ = x[RespErrJwtAccessTokenParsing-13]
	_ = x[RespErrJwtRefreshTokenCreate-14]
	_ = x[RespErrJwtRefreshTokenSigning-15]
	_ = x[RespErrJwtRefreshTokenUpdate-16]
	_ = x[RespErrJwtRefreshTokenParsing-17]
	_ = x[RespErrJwtRefreshTokenClaims-18]
	_ = x[RespErrJwtRefreshTokenInvalid-19]
	_ = x[RespErrJwtRefreshTokenExpired-20]
	_ = x[RespErrJwtRefreshTokenVerifyErr-21]
	_ = x[RespErrJwtRefreshTokenVerifyInvalid-22]
	_ = x[RespErrOauthCallbackCompleteAuth-23]
	_ = x[RespErrOauthCallbackUnknownError-24]
	_ = x[RespErrAuthLoginUnknownError-25]
	_ = x[RespErrAuthLoginNotLocal-26]
	_ = x[RespErrAuthSignupUnknownError-27]
	_ = x[RespErrAuthLogoutUnknownError-28]
	_ = x[RespErrLoginNoUser-29]
	_ = x[RespErrLoginComparePassword-30]
	_ = x[RespErrLoginWrongPassword-31]
	_ = x[RespErrSignupPasswordMismatch-32]
	_ = x[RespErrSignupPasswordHash-33]
	_ = x[RespErrSignupUserExists-34]
	_ = x[RespErrSignupNewUserOrg-35]
	_ = x[RespErrSignupUserCreate-36]
	_ = x[RespErrHookPreLogin-37]
	_ = x[RespErrHookPostLogin-38]
	_ = x[RespErrHookPreSignup-39]
	_ = x[RespErrHookSignupDefaultRole-40]
	_ = x[RespErrOauthReferrerParsing-41]
	_ = x[RespErrOauthMarshalState-42]
	_ = x[RespErrGetAccessClaims-43]
}

const _ResponseId_name = "RespSccsGenericRespSccsLoginRespSccsLogoutRespSccsSignupRespScssSignupEmailConfirmRespSccsAlreadyLoggedInRespErrUndefinedRespErrUnknownInternalRespErrCsrfInvalidRespErrUserDoesNotExistRespErrUserNoRolesRespErrMissingInputRespErrJwtAccessTokenSigningRespErrJwtAccessTokenParsingRespErrJwtRefreshTokenCreateRespErrJwtRefreshTokenSigningRespErrJwtRefreshTokenUpdateRespErrJwtRefreshTokenParsingRespErrJwtRefreshTokenClaimsRespErrJwtRefreshTokenInvalidRespErrJwtRefreshTokenExpiredRespErrJwtRefreshTokenVerifyErrRespErrJwtRefreshTokenVerifyInvalidRespErrOauthCallbackCompleteAuthRespErrOauthCallbackUnknownErrorRespErrAuthLoginUnknownErrorRespErrAuthLoginNotLocalRespErrAuthSignupUnknownErrorRespErrAuthLogoutUnknownErrorRespErrLoginNoUserRespErrLoginComparePasswordRespErrLoginWrongPasswordRespErrSignupPasswordMismatchRespErrSignupPasswordHashRespErrSignupUserExistsRespErrSignupNewUserOrgRespErrSignupUserCreateRespErrHookPreLoginRespErrHookPostLoginRespErrHookPreSignupRespErrHookSignupDefaultRoleRespErrOauthReferrerParsingRespErrOauthMarshalStateRespErrGetAccessClaims"

var _ResponseId_index = [...]uint16{0, 15, 28, 42, 56, 82, 105, 121, 143, 161, 184, 202, 221, 249, 277, 305, 334, 362, 391, 419, 448, 477, 508, 543, 575, 607, 635, 659, 688, 717, 735, 762, 787, 816, 841, 864, 887, 910, 929, 949, 969, 997, 1024, 1048, 1070}

func (i ResponseId) String() string {
	if i >= ResponseId(len(_ResponseId_index)-1) {
		return "ResponseId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseId_name[_ResponseId_index[i]:_ResponseId_index[i+1]]
}
