// Code generated by "stringer -type ResponseSuccessId -output ./stringer_ResponseSuccessId.go"; DO NOT EDIT.

package web_response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RespSccsGeneric-0]
}

const _ResponseSuccessId_name = "RespSccsGeneric"

var _ResponseSuccessId_index = [...]uint8{0, 15}

func (i ResponseSuccessId) String() string {
	if i >= ResponseSuccessId(len(_ResponseSuccessId_index)-1) {
		return "ResponseSuccessId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseSuccessId_name[_ResponseSuccessId_index[i]:_ResponseSuccessId_index[i+1]]
}
