// Code generated by "stringer -type ResponseErrorId -output ./stringer_ResponseErrorId.go"; DO NOT EDIT.

package web_response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RespErrNone-0]
	_ = x[RespErrUndefined-1]
	_ = x[RespErrUnknownInternal-2]
	_ = x[RespErrCsrfInvalid-3]
	_ = x[RespErrUserDoesNotExist-4]
	_ = x[RespErrUserNoRoles-5]
	_ = x[RespErrMissingInput-6]
	_ = x[RespErrJwtAccessTokenSigning-7]
	_ = x[RespErrJwtAccessTokenParsing-8]
	_ = x[RespErrJwtRefreshTokenCreate-9]
	_ = x[RespErrJwtRefreshTokenSigning-10]
	_ = x[RespErrJwtRefreshTokenUpdate-11]
	_ = x[RespErrJwtRefreshTokenParsing-12]
	_ = x[RespErrJwtRefreshTokenClaims-13]
	_ = x[RespErrJwtRefreshTokenInvalid-14]
	_ = x[RespErrJwtRefreshTokenExpired-15]
	_ = x[RespErrJwtRefreshTokenVerifyErr-16]
	_ = x[RespErrJwtRefreshTokenVerifyInvalid-17]
	_ = x[RespErrOauthCallbackCompleteAuth-18]
	_ = x[RespErrOauthCallbackUnknownError-19]
	_ = x[RespErrAuthLoginUnknownError-20]
	_ = x[RespErrAuthSignupUnknownError-21]
	_ = x[RespErrAuthLogoutUnknownError-22]
	_ = x[RespErrLoginNoUser-23]
	_ = x[RespErrLoginComparePassword-24]
	_ = x[RespErrLoginWrongPassword-25]
	_ = x[RespErrSignupPasswordMismatch-26]
	_ = x[RespErrSignupPasswordHash-27]
	_ = x[RespErrSignupUserExists-28]
	_ = x[RespErrSignupNewUserOrg-29]
	_ = x[RespErrSignupUserCreate-30]
	_ = x[RespErrHookPreLogin-31]
	_ = x[RespErrHookPostLogin-32]
	_ = x[RespErrHookPreSignup-33]
	_ = x[RespErrHookSignupDefaultRole-34]
}

const _ResponseErrorId_name = "RespErrNoneRespErrUndefinedRespErrUnknownInternalRespErrCsrfInvalidRespErrUserDoesNotExistRespErrUserNoRolesRespErrMissingInputRespErrJwtAccessTokenSigningRespErrJwtAccessTokenParsingRespErrJwtRefreshTokenCreateRespErrJwtRefreshTokenSigningRespErrJwtRefreshTokenUpdateRespErrJwtRefreshTokenParsingRespErrJwtRefreshTokenClaimsRespErrJwtRefreshTokenInvalidRespErrJwtRefreshTokenExpiredRespErrJwtRefreshTokenVerifyErrRespErrJwtRefreshTokenVerifyInvalidRespErrOauthCallbackCompleteAuthRespErrOauthCallbackUnknownErrorRespErrAuthLoginUnknownErrorRespErrAuthSignupUnknownErrorRespErrAuthLogoutUnknownErrorRespErrLoginNoUserRespErrLoginComparePasswordRespErrLoginWrongPasswordRespErrSignupPasswordMismatchRespErrSignupPasswordHashRespErrSignupUserExistsRespErrSignupNewUserOrgRespErrSignupUserCreateRespErrHookPreLoginRespErrHookPostLoginRespErrHookPreSignupRespErrHookSignupDefaultRole"

var _ResponseErrorId_index = [...]uint16{0, 11, 27, 49, 67, 90, 108, 127, 155, 183, 211, 240, 268, 297, 325, 354, 383, 414, 449, 481, 513, 541, 570, 599, 617, 644, 669, 698, 723, 746, 769, 792, 811, 831, 851, 879}

func (i ResponseErrorId) String() string {
	if i >= ResponseErrorId(len(_ResponseErrorId_index)-1) {
		return "ResponseErrorId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseErrorId_name[_ResponseErrorId_index[i]:_ResponseErrorId_index[i+1]]
}
